version: "3"
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATEBASE: root
      MYSQL_ROOT_PASSWORD: Makitest1 # 任意のパスワード
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails-fargate
    ports:
      - "3000:3000"
    depends_on:
      - db
