default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  charset: utf8
  encoding: utf8

development:
  <<: *default
  database: rails_fargate_development
  username: root # 必ずrootを指定すること
  password: Makitest1 # 任意のパスワード(MYSQL_ROOT_PASSWORDと同じにすること)
  host: db # 注意: ここlocalhostにしてはダメ

test:
  <<: *default
  username: root
  password: Makitest1
  database: rails_fargate_test
  host: db

production:
  <<: *default
  database: rails_fargate_production
  username: rails_fargate
  password: <%= ENV['RAILS_FARGATE_DATABASE_PASSWORD'] %>
